# Generated by Django 5.2.8 on 2025-11-17 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(help_text='实际探访人的姓名', max_length=50, verbose_name='探访人姓名')),
                ('visitor_gender', models.CharField(help_text='探访人性别，如：男、女', max_length=10, verbose_name='性别')),
                ('visitor_id_card', models.CharField(help_text='探访人的身份证号码，用于身份验证', max_length=18, verbose_name='身份证号')),
                ('visitor_phone', models.CharField(help_text='探访人的手机号码，用于联系', max_length=11, verbose_name='联系电话')),
                ('visitor_address', models.CharField(help_text='探访人的详细联系地址', max_length=200, verbose_name='联系地址')),
                ('prisoner_name', models.CharField(help_text='被探访的戒毒人员姓名', max_length=50, verbose_name='戒毒人员姓名')),
                ('relationship', models.CharField(help_text='探访人与戒毒人员的关系，如：父母、配偶、子女等', max_length=50, verbose_name='与戒毒人员关系')),
                ('appointment_reason', models.TextField(help_text='预约探访的具体原因', verbose_name='预约原因')),
                ('appointment_time', models.DateTimeField(help_text='计划探访的日期和时间', verbose_name='预约时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', help_text='预约的当前状态', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='预约记录的创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='预约记录的最后更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(help_text='创建该预约的用户', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='预约用户')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'db_table': 'appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelativeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='亲属的姓名', max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(help_text='亲属的性别，如：男、女', max_length=10, verbose_name='性别')),
                ('id_card', models.CharField(help_text='亲属的身份证号码，用于身份验证', max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(help_text='亲属的手机号码', max_length=11, verbose_name='联系电话')),
                ('relationship', models.CharField(help_text='该亲属与戒毒人员的关系，如：父母、配偶、子女等', max_length=50, verbose_name='与戒毒人员关系')),
                ('appointment', models.ForeignKey(help_text='与该亲属信息关联的预约记录', on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='appointments.appointment', verbose_name='关联预约')),
            ],
            options={
                'verbose_name': '亲属信息',
                'verbose_name_plural': '亲属信息',
                'db_table': 'relative_info',
            },
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(help_text='实际探访的日期和时间', verbose_name='探访时间')),
                ('actual_visitor', models.CharField(help_text='实际进行探访的人员姓名', max_length=50, verbose_name='实际探访人')),
                ('notes', models.TextField(blank=True, help_text='探访过程中的特殊情况或其他需要记录的信息', null=True, verbose_name='备注')),
                ('appointment', models.ForeignKey(help_text='与该探访记录关联的预约记录', on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='appointments.appointment', verbose_name='关联预约')),
            ],
            options={
                'verbose_name': '探访记录',
                'verbose_name_plural': '探访记录',
                'db_table': 'visit_records',
                'ordering': ['-visit_time'],
            },
        ),
    ]
