# Generated by Django 5.2.8 on 2025-11-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queue_month',
            field=models.IntegerField(blank=True, help_text='用户被分配的预约月份，格式为YYYYMM', null=True, verbose_name='预约月份'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_position',
            field=models.IntegerField(default=0, help_text='在该月份预约中的排队位置', verbose_name='排队位置'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成'), ('cancelled', '已取消'), ('queued', '排队中')], default='pending', help_text='预约的当前状态', max_length=20, verbose_name='状态'),
        ),
    ]
