# Generated by Django 5.2.8 on 2025-11-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_queue_month_appointment_queue_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(blank=True, help_text='计划探访的日期和时间', null=True, verbose_name='预约时间'),
        ),
    ]
