# Generated by Django 3.2.23 on 2025-12-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(help_text='时间段所属的探访日期', verbose_name='探访日期')),
                ('time_slot', models.CharField(help_text='时间段名称，格式：HH:MM-HH:MM', max_length=20, verbose_name='时间段')),
                ('start_time', models.TimeField(help_text='时间段的开始时间', verbose_name='开始时间')),
                ('end_time', models.TimeField(help_text='时间段的结束时间', verbose_name='结束时间')),
                ('total_quota', models.IntegerField(default=20, help_text='该时间段可预约的总批次数', verbose_name='总配额')),
                ('used_quota', models.IntegerField(default=0, help_text='该时间段已被预约的批次数', verbose_name='已用配额')),
                ('available_quota', models.IntegerField(default=20, help_text='该时间段剩余可预约的批次数', verbose_name='可用配额')),
                ('month', models.IntegerField(help_text='时间段所属的月份，格式为YYYYMM', verbose_name='所属月份')),
            ],
            options={
                'verbose_name': '时间段',
                'verbose_name_plural': '时间段',
                'db_table': 'time_slots',
                'ordering': ['visit_date', 'start_time'],
                'unique_together': {('visit_date', 'time_slot')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='分配给该预约的时间段', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.timeslot', verbose_name='时间段'),
        ),
    ]
