# Generated by Django 3.2.23 on 2025-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20251211_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.CharField(help_text='预约号，格式：年+月+当日提交顺序号（例如2025121213）', max_length=20, primary_key=True, serialize=False, verbose_name='预约号'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='available_quota',
            field=models.IntegerField(default=2, help_text='该时间段剩余可预约的批次数', verbose_name='可用配额'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='total_quota',
            field=models.IntegerField(default=2, help_text='该时间段可预约的总批次数', verbose_name='总配额'),
        ),
    ]
