# Generated by Django 3.2.23 on 2025-12-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20251216_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_date',
            field=models.DateField(blank=True, help_text='预约人指定的探访日期', null=True, verbose_name='探访日期'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(blank=True, help_text='计划探访的日期和时间（已废弃，保留用于兼容性）', null=True, verbose_name='预约时间'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='管理员分配的时间段', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.timeslot', verbose_name='时间段'),
        ),
    ]
