# Generated by Django 3.2.23 on 2025-12-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20251223_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='visit_date',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(blank=True, help_text='计划探访的日期和时间', null=True, verbose_name='预约时间'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='分配给该预约的时间段', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.timeslot', verbose_name='时间段'),
        ),
    ]
