# Generated by Django 3.2.23 on 2025-12-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20251223_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_date',
            field=models.DateField(blank=True, help_text='探访人指定的探访日期', null=True, verbose_name='探访日期'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, help_text='管理员选择的探访时间段（格式：HH:MM-HH:MM）', max_length=20, null=True, verbose_name='时间段'),
        ),
    ]
