# Generated by Django 3.2.23 on 2025-12-25 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20251223_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
