# Generated by Django 3.2.23 on 2025-12-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_delete_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='管理员审核预约时的备注信息，拒绝预约时为必填项', null=True, verbose_name='审核备注'),
        ),
    ]
