# Generated by Django 3.2.23 on 2026-01-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_approval_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(help_text='公告的唯一标识', primary_key=True, serialize=False, verbose_name='公告ID')),
                ('title', models.CharField(help_text='公告的标题，最多100个字符', max_length=100, verbose_name='公告标题')),
                ('publish_time', models.DateTimeField(auto_now_add=True, help_text='公告的发布时间', verbose_name='发布时间')),
                ('content', models.TextField(help_text='公告的详细内容', verbose_name='公告内容')),
                ('issuing_authority', models.CharField(help_text='发布公告的机关或部门', max_length=50, verbose_name='发布机关')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcements',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
    ]
