# Generated by Django 5.2.8 on 2025-11-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='用户的真实姓名', max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
