# Generated by Django 5.2.8 on 2025-11-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_full_name_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='用户的手机号码', max_length=11, null=True, verbose_name='电话号码'),
        ),
    ]
